# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b94a21a5acacd8b7de429068efc2e4ca757cb665519fe371480bed859f0211be55d81da47357f97d2a8b087ca79569179e6578d8185bafd3ec364d17dea0443

test:
  secret_key_base: 9fc5c05862135d6fa585e0a271a45f6b8bea7cffb7f5f41e059ac681ece9a756f4778cd55f5699f7214eae1d62b5fe9bf649c3ac9fbbef4252dec4100b648416

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
